### ISSUE TITLE
Adicione o nome no readme

### ISSUE THREAD

**Issue by RaphaelAlcantara** [RaphaelAlcantara/GCMS-Raphael-Alcantara#1]
[Readme] (https://github.com/RaphaelAlcantara/GCMS-Raphael-Alcantara/blob/main/README.md)

**Comment by ramidedantas** [comment]
@RaphaelAlcantara Formate o Readme como está no meu repositório, incluindo seu nome, depois me marque aqui.

**Comment by RaphaelAlcantara** [comment]
@ramidedantas Readme ajustado, aguardo sua colaboração

**Comment by ramidedantas** [comment]
@RaphaelAlcantara realizada alteração, pode fechar a issue.
